# Folders / Paths / Names
project_name: 'mask-rcnn-elba'
train_ds: 'elba/train_ann_labelme'
test_ds: 'elba/test_ann_labelme'
font_file: 'data/roboto.ttf'
# Train params
seed: 1234
img_size: 512

model_name: 'maskrcnn_resnet50_fpn_v2'
batch_size: 16
lr: 0.0005
epochs: 10